language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
env:
  - TASK=lint
  - TASK=test
  - TASK=coverage
before_script:
  - npm prune
script: "travis_wait 60 npm run $TASK"
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
